"""
HTML 리포트 생성 모듈
"""
import pandas as pd
import numpy as np
from pathlib import Path
from datetime import datetime
from typing import Dict
import base64
from io import BytesIO

try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    import seaborn as sns
    PLOT_AVAILABLE = True
except ImportError:
    PLOT_AVAILABLE = False


class HTMLReportGenerator:
    """모델 비교 결과 HTML 리포트 생성기"""

    def __init__(self):
        self.html_template = """
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>정신건강 예측 모델 비교 리포트</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        .header h1 {{
            margin: 0;
            font-size: 2.5em;
        }}
        .header p {{
            margin: 10px 0 0 0;
            opacity: 0.9;
        }}
        .section {{
            background: white;
            padding: 25px;
            margin-bottom: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h2 {{
            color: #667eea;
            border-bottom: 3px solid #667eea;
            padding-bottom: 10px;
            margin-top: 0;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background-color: #667eea;
            color: white;
            font-weight: bold;
        }}
        tr:hover {{
            background-color: #f5f5f5;
        }}
        .metric-card {{
            display: inline-block;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            margin: 10px;
            border-radius: 8px;
            min-width: 200px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        .metric-card h3 {{
            margin: 0;
            font-size: 0.9em;
            opacity: 0.9;
        }}
        .metric-card p {{
            margin: 10px 0 0 0;
            font-size: 2em;
            font-weight: bold;
        }}
        .best-model {{
            background-color: #4CAF50 !important;
            color: white;
            font-weight: bold;
        }}
        .chart-container {{
            margin: 30px 0;
            text-align: center;
        }}
        .chart-container img {{
            max-width: 100%;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        .feature-importance {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }}
        .feature-bar {{
            background: #f0f0f0;
            padding: 10px;
            border-radius: 5px;
        }}
        .feature-bar .bar {{
            background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
            height: 25px;
            border-radius: 3px;
            transition: width 0.3s ease;
        }}
        .feature-bar .label {{
            font-size: 0.9em;
            margin-bottom: 5px;
            font-weight: 500;
        }}
        .footer {{
            text-align: center;
            padding: 20px;
            color: #666;
            font-size: 0.9em;
        }}
        .badge {{
            display: inline-block;
            padding: 5px 10px;
            border-radius: 20px;
            font-size: 0.85em;
            font-weight: bold;
            margin: 0 5px;
        }}
        .badge-success {{ background-color: #4CAF50; color: white; }}
        .badge-warning {{ background-color: #ff9800; color: white; }}
        .badge-danger {{ background-color: #f44336; color: white; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🧠 정신건강 예측 모델 비교 리포트</h1>
        <p>생성 일시: {generation_time}</p>
        <p>분석 대상: {target_variable}</p>
    </div>

    {content}

    <div class="footer">
        <p>Generated by KLOSDOM Lifelog Pattern Data Generation System</p>
        <p>{generation_time}</p>
    </div>
</body>
</html>
"""

    def generate_report(
        self,
        results: Dict,
        summary_df: pd.DataFrame,
        target_variable: str,
        output_path: str
    ):
        """HTML 리포트 생성"""
        print(f"\n📄 HTML 리포트 생성 중...")

        content_sections = []

        # 1. 요약 섹션
        content_sections.append(self._generate_summary_section(summary_df))

        # 2. 모델별 상세 결과
        content_sections.append(self._generate_detailed_results(results))

        # 3. 특징 중요도
        content_sections.append(self._generate_feature_importance(results))

        # 4. 비교 차트 (있으면)
        if PLOT_AVAILABLE:
            chart_html = self._generate_comparison_charts(summary_df)
            if chart_html:
                content_sections.append(chart_html)

        # HTML 조합
        html_content = self.html_template.format(
            generation_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            target_variable=target_variable.upper(),
            content="\n".join(content_sections)
        )

        # 파일 저장
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)

        print(f"   ✓ 리포트 저장: {output_path}")
        return output_path

    def _generate_summary_section(self, summary_df: pd.DataFrame) -> str:
        """요약 섹션 생성"""
        best_model = summary_df.iloc[0]

        metrics_html = f"""
        <div class="metric-card">
            <h3>최고 성능 모델</h3>
            <p>{best_model['모델']}</p>
        </div>
        <div class="metric-card">
            <h3>Test R² Score</h3>
            <p>{best_model['Test R²']:.4f}</p>
        </div>
        <div class="metric-card">
            <h3>Test MAE</h3>
            <p>{best_model['Test MAE']:.4f}</p>
        </div>
        """

        table_html = summary_df.to_html(index=False, classes='table', border=0)
        # 최고 모델 행에 클래스 추가
        table_html = table_html.replace('<tr>', '<tr class="best-model">', 1)

        return f"""
        <div class="section">
            <h2>📊 모델 성능 요약</h2>
            {metrics_html}
            <div style="clear: both; margin-top: 30px;">
                {table_html}
            </div>
        </div>
        """

    def _generate_detailed_results(self, results: Dict) -> str:
        """모델별 상세 결과"""
        detailed_html = '<div class="section"><h2>📈 모델별 상세 결과</h2>'

        for model_name, result in results.items():
            if 'error' in result:
                continue

            detailed_html += f"""
            <h3>{result['model_name']}</h3>
            <table>
                <tr>
                    <th>지표</th>
                    <th>Train</th>
                    <th>Test</th>
                    <th>차이</th>
                </tr>
                <tr>
                    <td>R² Score</td>
                    <td>{result['train_r2']:.4f}</td>
                    <td>{result['test_r2']:.4f}</td>
                    <td>{result['train_r2'] - result['test_r2']:.4f}</td>
                </tr>
                <tr>
                    <td>MAE</td>
                    <td>{result['train_mae']:.4f}</td>
                    <td>{result['test_mae']:.4f}</td>
                    <td>{result['test_mae'] - result['train_mae']:.4f}</td>
                </tr>
                <tr>
                    <td>MSE</td>
                    <td>{result['train_mse']:.4f}</td>
                    <td>{result['test_mse']:.4f}</td>
                    <td>{result['test_mse'] - result['train_mse']:.4f}</td>
                </tr>
            </table>
            """

        detailed_html += '</div>'
        return detailed_html

    def _generate_feature_importance(self, results: Dict) -> str:
        """특징 중요도 섹션"""
        html = '<div class="section"><h2>🔍 특징 중요도</h2>'

        for model_name, result in results.items():
            if 'feature_importance' not in result:
                continue

            # 중요도 정렬
            importance = sorted(
                result['feature_importance'].items(),
                key=lambda x: x[1],
                reverse=True
            )[:10]  # 상위 10개만

            max_importance = max([imp for _, imp in importance])

            html += f'<h3>{result["model_name"]}</h3><div class="feature-importance">'

            for feature, imp in importance:
                width_pct = (imp / max_importance) * 100
                html += f"""
                <div class="feature-bar">
                    <div class="label">{feature}: {imp:.4f}</div>
                    <div class="bar" style="width: {width_pct}%;"></div>
                </div>
                """

            html += '</div>'

        html += '</div>'
        return html

    def _generate_comparison_charts(self, summary_df: pd.DataFrame) -> str:
        """비교 차트 생성"""
        if not PLOT_AVAILABLE:
            return ""

        html = '<div class="section"><h2>📊 시각화 비교</h2>'

        # R² 비교 차트
        fig, ax = plt.subplots(figsize=(10, 6))
        x = range(len(summary_df))
        width = 0.35

        ax.bar([i - width/2 for i in x], summary_df['Train R²'],
               width, label='Train R²', color='#667eea')
        ax.bar([i + width/2 for i in x], summary_df['Test R²'],
               width, label='Test R²', color='#764ba2')

        ax.set_xlabel('모델')
        ax.set_ylabel('R² Score')
        ax.set_title('모델별 R² Score 비교')
        ax.set_xticks(x)
        ax.set_xticklabels(summary_df['모델'])
        ax.legend()
        ax.grid(axis='y', alpha=0.3)

        # 이미지를 base64로 인코딩
        buffer = BytesIO()
        plt.tight_layout()
        plt.savefig(buffer, format='png', dpi=100, bbox_inches='tight')
        buffer.seek(0)
        image_base64 = base64.b64encode(buffer.read()).decode()
        plt.close()

        html += f'<div class="chart-container"><img src="data:image/png;base64,{image_base64}" /></div>'
        html += '</div>'

        return html
